language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
script:
  - py.test test_flask_redislite.py --pep8 flask_redislite.py -v --cov flask_redislite --cov-report term-missing
after_success: coveralls
matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.7'
